### ISSUE TITLE
Can I rely on snap hostnames being formatted the same way?

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_corr_cm#13]
I'd like to parse the node and snap number out and put them in separate columns so they can be sorted on, but before I do that I want to be sure the formatting will remain the same. Alternatively, could that info be added explicitly to the returned dict so I don't need to parse it in M&C?

**Comment by jack-h** [comment]
I can add that to the return dict or you can query it yourself -- it's stored in the hookup database (I'm pretty sure) if you query based on the SNAP serial (e.g. "heraSNAPA0004").
The formatting will probably always remain the same, but is never used for anything but human decoding of SNAP physical locations, and is not stored in any database anywhere.

**Comment by bhazelton** [comment]
Perfect, I'll query it directly using the serial number. Thanks!
