### ISSUE TITLE
get_f_status None values

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_corr_cm#14]
The docstring says that the values in the per-hostname dict can be None. Can all of them be None sometimes including the timestamp? Or are there some that won't be None?

**Comment by jack-h** [comment]
The way it's coded anything can in principle be "None" and the docstring is correct. In practice timestamp should never be None. Other values could be None in edge cases, mostly involving times when the FPGAs are incorrectly programmed.

**Comment by bhazelton** [comment]
Thanks!
