### ISSUE TITLE
What are "ADC Units"?

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_corr_cm#15]
referenced in get_ant_stats

**Comment by jack-h** [comment]
Aka ADC counts. I.e. raw ADC values interpreted as signed integers between
-128 and +127.

**Comment by bhazelton** [comment]
Ok. What should the mean, RMS and power be in these units? How does one tell what is good or bad?

**Comment by jack-h** [comment]
Mean is usually ~-0.5. Good RMS is somewhere ~10-20. Power in this case is just RMS^2. (mean is assumed ~0)

**Comment by bhazelton** [comment]
Thanks. So noted in the M&C docs.
