### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_corr_cm#19]
This was working before, but I just pulled and installed onsite and I'm now getting this error:
```---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-9d203d2f9e65> in <module>()
----> 1 import hera_corr_cm

/home/obs/src/hera_corr_cm/hera_corr_cm/__init__.py in <module>()
----> 1 from __version__ import __version__
      2 
      3 from hera_corr_cm import *
      4 import helpers

ImportError: No module named __version__
```

**Comment by jack-h** [comment]
I can import hera_corr_cm fine both on hera-snap-head and on qmaster on
site.

??

**Comment by bhazelton** [comment]
Sorry! It works unless I'm in the `hera_corr_cm` directory, where I get this error. I'm usually not in that folder so it's not a problem (although it is a little weird).
