### ISSUE TITLE
Still getting unsafe yaml loading warnings.

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_corr_cm#23]
: /home/obs/anaconda/envs/HERA/lib/python2.7/site-packages/hera_corr_cm/hera_corr_cm.py:572: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

**Comment by jack-h** [comment]
[should be] fixed in f35b978

installed on qmaster
