### ISSUE TITLE
take data timing out

### ISSUE THREAD

**Issue by mkolopanis** [HERA-Team/hera_corr_cm#27]
issuing the command `correlator_control.py take_data .....` will sometimes return an "ERROR" state. This was noticed on the `python3` branch while running on `hera-corr-head`.

 The lack of error messages from corr_cm leads me to believe it is from a message timeout, however the correlator  will still start an observation successfully and observe with the given parameters

**Comment by jack-h** [comment]
Timeout was increased to 120 seconds as part of the BDA merge (BDA takes longer to start because it computes baseline configuration from MC). This seems to be adequate to fix this issue.
