### ISSUE TITLE
Open redis connections with decode_responses=True

### ISSUE THREAD

**Issue by plaplant** [HERA-Team/hera_corr_cm#37]
According to this StackOverflow page, there's a way to have redis automagically decode responses from bytes into strings:

https://stackoverflow.com/a/44032018

I'm hoping it's as simple as just passing the `decode_responses=True` keyword argument into any places where we instantiate a redis connection. There will likely be knock-on effects (like how now in some places we're indexing dictionaries with bytes instead of strings), but I think it would make everything cleaner on the whole, especially because we need to be py2/py3 compatible for the foreseeable future.

**Comment by mkolopanis** [comment]
this has been implemented in #36
