### ISSUE TITLE
Return time stamps associated with state info

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_corr_cm#4]
like `is_recording`, `phase_switch_is_on` and `noise_diode_is_on`

If so, it would be good to get that time stamp returned as well.
Also, are they reported on a cadence? Should I expect the same timestamps across these different status values or not?

**Comment by jack-h** [comment]
They are not reported on a cadence -- the values are set when the state changes. I.e., the correlator call which turns on phase switching sets the `phase_switch_is_on` redis keyword. It could report the time that it does this. Were timestamps of this type to be implemented, you should definitely expect them to differ over the different state keys.

**Comment by bhazelton** [comment]
Ok, that makes sense. I think we need to have the timestamps returned so that we can make a monitoring table with the timestamps of the changes in it, but I'll construct the table so that each command has its own timestamp.

**Comment by bhazelton** [comment]
I believe this works now.
