### ISSUE TITLE
Clarify the `acclen` argument to `take_data`

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_corr_cm#6]
I'm not sure what this parameter means or how it should be set. If it is really controlling the accumulation length in seconds of the visibilities it should at a minimum have good defaulting in M&C (and maybe be hard to change?)

**Comment by bhazelton** [comment]
Also: should duration be a float or an int?

**Comment by bhazelton** [comment]
we need a function to return what a given acclen gives for integration time in seconds

**Comment by jack-h** [comment]
Clarified data types and meaning.

Added functions to go between time (seconds) and n_spectra.
