### ISSUE TITLE
Can the config be updated while recording?

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_corr_cm#9]
It looks like update_config can be called while the correlator is recording. Should that be allowed?

**Comment by jack-h** [comment]
It can be updated, but the update won't take effect until the correlator is re-initialized. The code could explicitly prevent this from being allowed. You can also side-load config files at initialization time directly, so the config in redis should not be trusted to be the running config.
There is a redis key which tells you the config used at initialization time, as well as any command line options which were passed. This is not currently exposed unless you query the redis database directly

**Comment by bhazelton** [comment]
Hmm, I think that what we want to know in M&C is what config is actually being used by the correlator at any given time.

**Comment by bhazelton** [comment]
This is handled in with the new `get_version` method.
